### ISSUE TITLE
Completely destroyed burp-ui

### ISSUE THREAD

**Issue by jazzdd86** [pschiffe/docker-burp#1]
When I start the burp-ui and display it with chrome or firefox it shows as the screenshot below. What's wrong here?

![bildschirmfoto vom 2017-03-08 10-32-49](https://cloud.githubusercontent.com/assets/10222385/23698139/b33fb42c-03ea-11e7-900f-feb79af33f3f.png)

**Comment by pschiffe** [comment]
Yeah, I saw that in one case. I looks like the gunicorn is not able to server static content, but I don't know why. As of now, one solution I see is to put nginx serving static content in front of gunicorn.. But then I will need to run systemd inside of the container to manage multiple processes.

Another solution is to provide additional image with only nginx and static content, which would forward requests to the burp-ui container. But I like the first option better I guess.

**Comment by jazzdd86** [comment]
works now - I recreated the container several times and now it is working....
