### ISSUE TITLE
Regular builds, tagging version numbers, etc.

### ISSUE THREAD

**Issue by TheNotary** [pschiffe/docker-burp#3]
This looks pretty great, though with only 14 commits, I do wonder how much time was spent ensuring consistent behavior.  If you're maintaining this, would you consider automating regular builds of this project and tagging them with what versions of `burp-server` are being used in the image?

**Comment by pschiffe** [comment]
Hello @TheNotary . I'm sorry for the late response. I've just rebased the images to the latest base image and added a couple of improvements. I have configured the automated builds for this repo on docker hub, so the images are automatically built after a push to this repo. Unfortunately, these automated builds don't support adding multiple tags to one image, so there's only this `latest` tag available.
