### ISSUE TITLE
Updated burp image

### ISSUE THREAD

**Issue by gauravsuman007** [pschiffe/docker-burp#6]
Hi,

Thanks for the work, I just stumbled upon it while looking for a containerised web UI deployment for burp.

I checked on docker hub and the last updated image was pushed 2 years ago. Do you plan to push newer images in the future?

Thanks

**Comment by pschiffe** [comment]
Hi @gauravsuman007, I know this is a late answer, but I've just resurrected these images a bit and updated them in the docker hub.
